/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct minifyjpeg_res {
	int errno;
	union {
		char *minified_jpeg_val;
	} minifyjpeg_res_u;
};
typedef struct minifyjpeg_res minifyjpeg_res;

struct minify_jpeg_proc_1_argument {
	char *arg1;
	int arg2;
	int arg3;
};
typedef struct minify_jpeg_proc_1_argument minify_jpeg_proc_1_argument;

#define MINIFY_JPEG_PROG 0x20000001
#define MINIFY_JPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFY_JPEG_PROC 1
extern  minifyjpeg_res * minify_jpeg_proc_1(char *, int , int , CLIENT *);
extern  minifyjpeg_res * minify_jpeg_proc_1_svc(char *, int , int , struct svc_req *);
extern int minify_jpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFY_JPEG_PROC 1
extern  minifyjpeg_res * minify_jpeg_proc_1();
extern  minifyjpeg_res * minify_jpeg_proc_1_svc();
extern int minify_jpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_minifyjpeg_res (XDR *, minifyjpeg_res*);
extern  bool_t xdr_minify_jpeg_proc_1_argument (XDR *, minify_jpeg_proc_1_argument*);

#else /* K&R C */
extern bool_t xdr_minifyjpeg_res ();
extern bool_t xdr_minify_jpeg_proc_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
