/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct jpeg_in {
	char *arg1;
};
typedef struct jpeg_in jpeg_in;

struct jpeg_out {
	char *res1;
};
typedef struct jpeg_out jpeg_out;

#define MINIFY_JPEG_PROG 0x20000001
#define MINIFY_JPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFY_JPEG_PROC 1
extern  jpeg_out * minify_jpeg_proc_1(jpeg_in *, CLIENT *);
extern  jpeg_out * minify_jpeg_proc_1_svc(jpeg_in *, struct svc_req *);
extern int minify_jpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFY_JPEG_PROC 1
extern  jpeg_out * minify_jpeg_proc_1();
extern  jpeg_out * minify_jpeg_proc_1_svc();
extern int minify_jpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_jpeg_in (XDR *, jpeg_in*);
extern  bool_t xdr_jpeg_out (XDR *, jpeg_out*);

#else /* K&R C */
extern bool_t xdr_jpeg_in ();
extern bool_t xdr_jpeg_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
